
define(['QUnit',
        'lib/chess/chess-engine',
        'lib/chess/pgn-parser',
        'lib/chess/huffman',
        'lib/underscore',
        'lib/chess/util',
        'lib/chess/index-parse'],
  function(Q, engine, pgn, huffman, underscore, util, index) {
    var lines  = [
      '[Event "6th London Classic 2014"]',
      '[Site "London ENG"]',
      '[Date "2014.12.10"]',
      '[Round "1.3"]',
      '[White "Nakamura,Hi"]',
      '[Black "Giri,A"]',
      '[Result "1/2-1/2"]',
      '[WhiteTitle "GM"]',
      '[BlackTitle "GM"]',
      '[WhiteElo "2775"]',
      '[BlackElo "2768"]',
      '[ECO "C67"]',
      '[Opening "Ruy Lopez"]',
      '[Variation "Berlin defence, open variation"]',
      '[WhiteFideId "2016192"]',
      '[BlackFideId "24116068"]',
      '[EventDate "2014.12.10"]',
      '',
      '1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. O-O Nxe4 5. Re1 Nd6 6. Nxe5 Be7 7. Bf1 Nxe5 8.',
      'Rxe5 O-O 9. Nc3 Ne8 10. Nd5 Bd6 11. Re2 Nf6 12. Ne3 Re8 13. b3 Bf8 14. Bb2 Re6',
      '15. c4 c6 16. Re1 d5 17. cxd5 Nxd5 18. Bc4 Nxe3 19. fxe3 Rh6 20. Rf1 Be6 21.',
      'Bxe6 Rxe6 22. Qf3 Qe8 23. Rf2 Rd8 24. Raf1 Rd7 25. Qf5 Red6 26. Qc2 Rh6 27. g3',
      'c5 28. Rf5 b6 29. R1f2 Re6 30. Qc3 Red6 31. Qc2 Re6 32. Qc3 Red6 33. Qc2 Re6 1/2-1/2',
      ''];
    
    return {
      test: function() {
        Q.test("test pgn parse", function(assert) {
          var result = pgn.parseGame(lines);
          var expected = {
            "moves": [
              "e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Nxe4",
              "Re1", "Nd6", "Nxe5", "Be7", "Bf1", "Nxe5", "Rxe5", "O-O",
              "Nc3", "Ne8", "Nd5", "Bd6", "Re2", "Nf6", "Ne3", "Re8",
              "b3", "Bf8", "Bb2", "Re6", "c4", "c6", "Re1", "d5",
              "cxd5", "Nxd5", "Bc4", "Nxe3", "fxe3", "Rh6", "Rf1", "Be6",
              "Bxe6", "Rxe6", "Qf3", "Qe8", "Rf2", "Rd8", "Raf1", "Rd7",
              "Qf5", "Red6", "Qc2", "Rh6", "g3", "c5", "Rf5", "b6",
              "R1f2", "Re6", "Qc3", "Red6", "Qc2", "Re6", "Qc3", "Red6",
              "Qc2", "Re6"
            ],
            "tags": [
              {
                "key": "Event",
                "value": "6th London Classic 2014"
              },
              {
                "key": "Site",
                "value": "London ENG"
              },
              {
                "key": "Date",
                "value": "2014.12.10"
              },
              {
                "key": "Round",
                "value": "1.3"
              },
              {
                "key": "White",
                "value": "Nakamura,Hi"
              },
              {
                "key": "Black",
                "value": "Giri,A"
              },
              {
                "key": "Result",
                "value": "1/2-1/2"
              },
              {
                "key": "WhiteTitle",
                "value": "GM"
              },
              {
                "key": "BlackTitle",
                "value": "GM"
              },
              {
                "key": "WhiteElo",
                "value": "2775"
              },
              {
                "key": "BlackElo",
                "value": "2768"
              },
              {
                "key": "ECO",
                "value": "C67"
              },
              {
                "key": "Opening",
                "value": "Ruy Lopez"
              },
              {
                "key": "Variation",
                "value": "Berlin defence, open variation"
              },
              {
                "key": "WhiteFideId",
                "value": "2016192"
              },
              {
                "key": "BlackFideId",
                "value": "24116068"
              },
              {
                "key": "EventDate",
                "value": "2014.12.10"
              }
            ]
          };
          assert.deepEqual(result, expected);
        });

        Q.test("test index parse", function(assert) {
          var parsedGame = pgn.parseGame(lines);
          var documents = index.parse(parsedGame);
          var expected = [
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AACQJAm0bVvIWeMZ6wR693znvruwHg==",
              "fromFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
              "goodNess": 0,
              "id": "c4d4e2d44d0174abe65d0711a3a33b1a",
              "month": 12,
              "move": "e4",
              "moveIndex": 0,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 15,
              "toFen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AgBAEgm0bVvIWeMZ6wR693znvruwHg==",
              "fromFen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
              "goodNess": 0,
              "id": "a4f803dab0a8301b9e4673474deaa3f1",
              "month": 12,
              "move": "e5",
              "moveIndex": 1,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 18,
              "toFen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UgAASSTQalvIWeMZ6wR693znvruwHg==",
              "fromFen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2",
              "goodNess": 0,
              "id": "776b1294133c8f902ef44732f939f316",
              "month": 12,
              "move": "Nf3",
              "moveIndex": 2,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 27,
              "toFen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UmABkEQCrbaFnDWe4QR693znvruwHg==",
              "fromFen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2",
              "goodNess": 0,
              "id": "02edb4461ce08561d1bc8529092619a8",
              "month": 12,
              "move": "Nc6",
              "moveIndex": 3,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 25,
              "toFen": "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UiywAUkk0GpbyDGesU6g13znvruwHg==",
              "fromFen": "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
              "goodNess": 0,
              "id": "79ea0dd6c55b221e4036f4c938165eb3",
              "month": 12,
              "move": "Bb5",
              "moveIndex": 4,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 21,
              "toFen": "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UmCBbZBEAq22hZw1Hk6gd893uruwHg==",
              "fromFen": "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
              "goodNess": 0,
              "id": "4b6a3a873603a215847668c22f85e738",
              "month": 12,
              "move": "Nf6",
              "moveIndex": 5,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 6,
              "toFen": "r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UiwWG0xJJNBqW8gxnuEEennnvruwHg==",
              "fromFen": "r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
              "goodNess": 0,
              "id": "d52366dcb1763b58e6b41b18f1af541b",
              "month": 12,
              "move": "O-O",
              "moveIndex": 6,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 16,
              "toFen": "r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UmCx2QZJJNBqW8hZ43EEes13usOwBg==",
              "fromFen": "r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4",
              "goodNess": 0,
              "id": "a27941aa49dc4a9907ef488882c54f79",
              "month": 12,
              "move": "Nxe4",
              "moveIndex": 7,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 27,
              "toFen": "r1bqkb1r/pppp1ppp/2n5/1B2p3/4n3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 0 5",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "srDABlMSCbTaFnKMZziBut65L7uQGA==",
              "fromFen": "r1bqkb1r/pppp1ppp/2n5/1B2p3/4n3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 0 5",
              "goodNess": 0,
              "id": "9481b199012d9de4716e89547c12c5fb",
              "month": 12,
              "move": "Re1",
              "moveIndex": 8,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 20,
              "toFen": "r1bqkb1r/pppp1ppp/2n5/1B2p3/4n3/5N2/PPPP1PPP/RNBQR1K1 b kq - 1 5",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "doEFtkESCbTaFnLWeA6BXvOdLsOwBg==",
              "fromFen": "r1bqkb1r/pppp1ppp/2n5/1B2p3/4n3/5N2/PPPP1PPP/RNBQR1K1 b kq - 1 5",
              "goodNess": 0,
              "id": "6fe5734fe102b6d3dc0fbea920f5cb37",
              "month": 12,
              "move": "Nd6",
              "moveIndex": 9,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 5,
              "toFen": "r1bqkb1r/pppp1ppp/2nn4/1B2p3/8/5N2/PPPP1PPP/RNBQR1K1 w kq - 2 6",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AmvBBlMSCbTaFnKMZziBct+5L7uQGA==",
              "fromFen": "r1bqkb1r/pppp1ppp/2nn4/1B2p3/8/5N2/PPPP1PPP/RNBQR1K1 w kq - 2 6",
              "goodNess": 0,
              "id": "f69778cfbd69d2dffed6e3442a45e92c",
              "month": 12,
              "move": "Nxe5",
              "moveIndex": 10,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 27,
              "toFen": "r1bqkb1r/pppp1ppp/2nn4/1B2N3/8/8/PPPP1PPP/RNBQR1K1 b kq - 0 6",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "LADsbZBEAq22hZw1nkOg13ynC8OwBg==",
              "fromFen": "r1bqkb1r/pppp1ppp/2nn4/1B2N3/8/8/PPPP1PPP/RNBQR1K1 b kq - 0 6",
              "goodNess": 0,
              "id": "b5bdbe0ded97e0c2687e16c0d6f739a0",
              "month": 12,
              "move": "Be7",
              "moveIndex": 11,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 20,
              "toFen": "r1bqk2r/ppppbppp/2nn4/1B2N3/8/8/PPPP1PPP/RNBQR1K1 w kq - 1 7",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "NqwFwJRkJNBqW8gxHk6g3HfuC7uQGA==",
              "fromFen": "r1bqk2r/ppppbppp/2nn4/1B2N3/8/8/PPPP1PPP/RNBQR1K1 w kq - 1 7",
              "goodNess": 0,
              "id": "eeaf017d353756c5412439d04f249425",
              "month": 12,
              "move": "Bf1",
              "moveIndex": 12,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 9,
              "toFen": "r1bqk2r/ppppbppp/2nn4/4N3/8/8/PPPP1PPP/RNBQRBK1 b kq - 2 7",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "LADsDUkk0M62hZw1njMEenmnC8OwBg==",
              "fromFen": "r1bqk2r/ppppbppp/2nn4/4N3/8/8/PPPP1PPP/RNBQRBK1 b kq - 2 7",
              "goodNess": 0,
              "id": "6f76c6fa8c3d6b61c0cc182307baae08",
              "month": 12,
              "move": "Nxe5",
              "moveIndex": 13,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 1,
              "toFen": "r1bqk2r/ppppbppp/3n4/4n3/8/8/PPPP1PPP/RNBQRBK1 w kq - 0 8",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "FlgAkGQk0GpbyDEeTqDmfee+u5AY",
              "fromFen": "r1bqk2r/ppppbppp/3n4/4n3/8/8/PPPP1PPP/RNBQRBK1 w kq - 0 8",
              "goodNess": 0,
              "id": "81ff02906d898933c2be8144578f2c71",
              "month": 12,
              "move": "Rxe5",
              "moveIndex": 14,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 0,
              "toFen": "r1bqk2r/ppppbppp/3n4/4R3/8/8/PPPP1PPP/RNBQ1BK1 b kq - 0 8",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "HABskEQC7WxbyFnjMQR6eacLw7AG",
              "fromFen": "r1bqk2r/ppppbppp/3n4/4R3/8/8/PPPP1PPP/RNBQ1BK1 b kq - 0 8",
              "goodNess": 0,
              "id": "f748f8d355aa33d2aadd58c4b042ff02",
              "month": 12,
              "move": "O-O",
              "moveIndex": 15,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 10,
              "toFen": "r1bq1rk1/ppppbppp/3n4/4R3/8/8/PPPP1PPP/RNBQ1BK1 w - - 1 9",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "LlgAkGQk0GpbyDEeR6Cmd+4Lw5AA",
              "fromFen": "r1bq1rk1/ppppbppp/3n4/4R3/8/8/PPPP1PPP/RNBQ1BK1 w - - 1 9",
              "goodNess": 0,
              "id": "80fadfa369673bf66d4b64a2054e2408",
              "month": 12,
              "move": "Nc3",
              "moveIndex": 16,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 34,
              "toFen": "r1bq1rk1/ppppbppp/3n4/4R3/8/2N5/PPPP1PPP/R1BQ1BK1 b - - 2 9",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "HCzABkkk0M62hRzjMQTqeqcLw5AA",
              "fromFen": "r1bq1rk1/ppppbppp/3n4/4R3/8/2N5/PPPP1PPP/R1BQ1BK1 b - - 2 9",
              "goodNess": 0,
              "id": "acde45ecf35f928f7c192bde6359355c",
              "month": 12,
              "move": "Ne8",
              "moveIndex": 17,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 2,
              "toFen": "r1bqnrk1/ppppbppp/8/4R3/8/2N5/PPPP1PPP/R1BQ1BK1 w - - 3 10",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "LgDYkGQk0GpbyDGedQRqeqcLw5AA",
              "fromFen": "r1bqnrk1/ppppbppp/8/4R3/8/2N5/PPPP1PPP/R1BQ1BK1 w - - 3 10",
              "goodNess": 0,
              "id": "dae15052a655fb06d21e567849e7625d",
              "month": 12,
              "move": "Nd5",
              "moveIndex": 18,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 32,
              "toFen": "r1bqnrk1/ppppbppp/8/3NR3/8/8/PPPP1PPP/R1BQ1BK1 b - - 4 10",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "nAUAkEQC7WxbyDEeQ6DufqcLw5AA",
              "fromFen": "r1bqnrk1/ppppbppp/8/3NR3/8/8/PPPP1PPP/R1BQ1BK1 b - - 4 10",
              "goodNess": 0,
              "id": "4c54b93cce07da435422f22aa4fe182c",
              "month": 12,
              "move": "Bd6",
              "moveIndex": 19,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 3,
              "toFen": "r1bqnrk1/pppp1ppp/3b4/3NR3/8/8/PPPP1PPP/R1BQ1BK1 w - - 5 11",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "+4IBAEkk0GpbyDGedQRqeqcLw5AA",
              "fromFen": "r1bqnrk1/pppp1ppp/3b4/3NR3/8/8/PPPP1PPP/R1BQ1BK1 w - - 5 11",
              "goodNess": 0,
              "id": "ee6464a9968600be40c2a4c34dd5d3e8",
              "month": 12,
              "move": "Re2",
              "moveIndex": 20,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 13,
              "toFen": "r1bqnrk1/pppp1ppp/3b4/3N4/8/8/PPPPRPPP/R1BQ1BK1 b - - 6 11",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "WABMkOQk0GpbyDEeQ6DufqcLw5AA",
              "fromFen": "r1bqnrk1/pppp1ppp/3b4/3N4/8/8/PPPPRPPP/R1BQ1BK1 b - - 6 11",
              "goodNess": 0,
              "id": "114afa04f7c393d5726f41cb4d94b557",
              "month": 12,
              "move": "Nf6",
              "moveIndex": 21,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 24,
              "toFen": "r1bq1rk1/pppp1ppp/3b1n2/3N4/8/8/PPPPRPPP/R1BQ1BK1 w - - 7 12",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "GxgWAEkk0N62hRzjcQRqeqcLw5AA",
              "fromFen": "r1bq1rk1/pppp1ppp/3b1n2/3N4/8/8/PPPPRPPP/R1BQ1BK1 w - - 7 12",
              "goodNess": 0,
              "id": "c3a2a87731193b8f1c5490a340dd312f",
              "month": 12,
              "move": "Ne3",
              "moveIndex": 22,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 0,
              "toFen": "r1bq1rk1/pppp1ppp/3b1n2/8/8/4N3/PPPPRPPP/R1BQ1BK1 b - - 8 12",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AAvbBElOAq22hRzjMQTqeqcLw5AA",
              "fromFen": "r1bq1rk1/pppp1ppp/3b1n2/8/8/4N3/PPPPRPPP/R1BQ1BK1 b - - 8 12",
              "goodNess": 0,
              "id": "180843d2e690a6b5ed8d8c1967ecaa07",
              "month": 12,
              "move": "Re8",
              "moveIndex": 23,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 18,
              "toFen": "r1bqr1k1/pppp1ppp/3b1n2/8/8/4N3/PPPPRPPP/R1BQ1BK1 w - - 9 13",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "gGFhA0kk0N62hRzjOQRqeqcLw5AA",
              "fromFen": "r1bqr1k1/pppp1ppp/3b1n2/8/8/4N3/PPPPRPPP/R1BQ1BK1 w - - 9 13",
              "goodNess": 0,
              "id": "a6efde0b5b54bf7c364da51ed1bbc528",
              "month": 12,
              "move": "b3",
              "moveIndex": 24,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 11,
              "toFen": "r1bqr1k1/pppp1ppp/3b1n2/8/8/1P2N3/P1PPRPPP/R1BQ1BK1 b - - 0 13",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AAvbhEhOAq22hRzjMQTKfacLw5AA",
              "fromFen": "r1bqr1k1/pppp1ppp/3b1n2/8/8/1P2N3/P1PPRPPP/R1BQ1BK1 b - - 0 13",
              "goodNess": 0,
              "id": "3d4bb681762468f1abf33751c7d811a1",
              "month": 12,
              "move": "Bf8",
              "moveIndex": 25,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 2,
              "toFen": "r1bqrbk1/pppp1ppp/5n2/8/8/1P2N3/P1PPRPPP/R1BQ1BK1 w - - 1 14",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "ABY2RRIJtLdVyDGeMwRqeqcLw5AA",
              "fromFen": "r1bqrbk1/pppp1ppp/5n2/8/8/1P2N3/P1PPRPPP/R1BQ1BK1 w - - 1 14",
              "goodNess": 0,
              "id": "2d22f4988ba526878160bba27894260d",
              "month": 12,
              "move": "Bb2",
              "moveIndex": 26,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 12,
              "toFen": "r1bqrbk1/pppp1ppp/5n2/8/8/1P2N3/PBPPRPPP/R2Q1BK1 b - - 2 14",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AAsbyEhOAq22hRweQ6DmfacLw5AA",
              "fromFen": "r1bqrbk1/pppp1ppp/5n2/8/8/1P2N3/PBPPRPPP/R2Q1BK1 b - - 2 14",
              "goodNess": 0,
              "id": "f0b5ecf2b6c0d1ecc609343a55d3e29f",
              "month": 12,
              "move": "Re6",
              "moveIndex": 27,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 18,
              "toFen": "r1bq1bk1/pppp1ppp/4rn2/8/8/1P2N3/PBPPRPPP/R2Q1BK1 w - - 3 15",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AGdhUySRQHvbWcgxHkOgppcLw5AA",
              "fromFen": "r1bq1bk1/pppp1ppp/4rn2/8/8/1P2N3/PBPPRPPP/R2Q1BK1 w - - 3 15",
              "goodNess": 0,
              "id": "1dfe60a6f78c80a8bad219be08143f87",
              "month": 12,
              "move": "c4",
              "moveIndex": 28,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 24,
              "toFen": "r1bq1bk1/pppp1ppp/4rn2/8/2P5/1P2N3/PB1PRPPP/R2Q1BK1 b - c3 0 15",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "ICzsCzLkJNBqW8jhMQRqeqcLw5AA",
              "fromFen": "r1bq1bk1/pppp1ppp/4rn2/8/2P5/1P2N3/PB1PRPPP/R2Q1BK1 b - c3 0 15",
              "goodNess": 0,
              "id": "468b10cb4fa3870198f7827f8c78791b",
              "month": 12,
              "move": "c6",
              "moveIndex": 29,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 15,
              "toFen": "r1bq1bk1/pp1p1ppp/2p1rn2/8/2P5/1P2N3/PB1PRPPP/R2Q1BK1 w - - 0 16",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UHEWNkVEAu2tWcgxHkOgppcLw5AA",
              "fromFen": "r1bq1bk1/pp1p1ppp/2p1rn2/8/2P5/1P2N3/PB1PRPPP/R2Q1BK1 w - - 0 16",
              "goodNess": 0,
              "id": "7eb1d643b5f2fb121f61f70dec6e138d",
              "month": 12,
              "move": "Re1",
              "moveIndex": 30,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 6,
              "toFen": "r1bq1bk1/pp1p1ppp/2p1rn2/8/2P5/1P2N3/PB1P1PPP/R2QRBK1 b - - 1 16",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "ICzsq8gQCbSqhRyeMwRqeqcLw5AA",
              "fromFen": "r1bq1bk1/pp1p1ppp/2p1rn2/8/2P5/1P2N3/PB1P1PPP/R2QRBK1 b - - 1 16",
              "goodNess": 0,
              "id": "852b9eda3c3e99fc33d9913270b117c1",
              "month": 12,
              "move": "d5",
              "moveIndex": 31,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 6,
              "toFen": "r1bq1bk1/pp3ppp/2p1rn2/3p4/2P5/1P2N3/PB1P1PPP/R2QRBK1 w - d6 0 17",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QcVZ2BRBAq2ahRzjMQRq3pcLw5AA",
              "fromFen": "r1bq1bk1/pp3ppp/2p1rn2/3p4/2P5/1P2N3/PB1P1PPP/R2QRBK1 w - d6 0 17",
              "goodNess": 0,
              "id": "6b366e95665870c7d53ff508a9af71db",
              "month": 12,
              "move": "cxd5",
              "moveIndex": 32,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 0,
              "toFen": "r1bq1bk1/pp3ppp/2p1rn2/3P4/8/1P2N3/PB1P1PPP/R2QRBK1 b - - 0 17",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "CCzsq8gQCbRoIYfnDIGa3ukCw5AA",
              "fromFen": "r1bq1bk1/pp3ppp/2p1rn2/3P4/8/1P2N3/PB1P1PPP/R2QRBK1 b - - 0 17",
              "goodNess": 0,
              "id": "ccd80dc5ccb65f393429fa1aaa0d04ce",
              "month": 12,
              "move": "Nxd5",
              "moveIndex": 33,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 31,
              "toFen": "r1bq1bk1/pp3ppp/2p1r3/3n4/8/1P2N3/PB1P1PPP/R2QRBK1 w - - 0 18",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "C8SBTREk0KpZyDEeQ6DmfbnDkAA=",
              "fromFen": "r1bq1bk1/pp3ppp/2p1r3/3n4/8/1P2N3/PB1P1PPP/R2QRBK1 w - - 0 18",
              "goodNess": 0,
              "id": "debb4a6a88331e00f4d77ae4213c41a0",
              "month": 12,
              "move": "Bc4",
              "moveIndex": 34,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 2,
              "toFen": "r1bq1bk1/pp3ppp/2p1r3/3n4/2B5/1P2N3/PB1P1PPP/R2QR1K1 b - - 1 18",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "2AYLriJDJNCihRyeQ6Cmd7rDkAA=",
              "fromFen": "r1bq1bk1/pp3ppp/2p1r3/3n4/2B5/1P2N3/PB1P1PPP/R2QR1K1 b - - 1 18",
              "goodNess": 0,
              "id": "af03121c735269d68ca546929f20aee3",
              "month": 12,
              "move": "Nxe3",
              "moveIndex": 35,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 39,
              "toFen": "r1bq1bk1/pp3ppp/2p1r3/8/2B5/1P2n3/PB1P1PPP/R2QR1K1 w - - 0 19",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "MMWBRREk0KpZyDEeQ6DclwvDkAA=",
              "fromFen": "r1bq1bk1/pp3ppp/2p1r3/8/2B5/1P2n3/PB1P1PPP/R2QR1K1 w - - 0 19",
              "goodNess": 0,
              "id": "463adf2ff5c2fe8a73d8a784769f4f03",
              "month": 12,
              "move": "fxe3",
              "moveIndex": 36,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 9,
              "toFen": "r1bq1bk1/pp3ppp/2p1r3/8/2B5/1P2P3/PB1P2PP/R2QR1K1 b - - 0 19",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "YBC4igwh0KKFHJ5DoKZ3usOQAA==",
              "fromFen": "r1bq1bk1/pp3ppp/2p1r3/8/2B5/1P2P3/PB1P2PP/R2QR1K1 b - - 0 19",
              "goodNess": 0,
              "id": "bb0566ca028657298a9c6ced45b51a59",
              "month": 12,
              "move": "Rh6",
              "moveIndex": 37,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 6,
              "toFen": "r1bq1bk1/pp3ppp/2p4r/8/2B5/1P2P3/PB1P2PP/R2QR1K1 w - - 1 20",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "MAUoRZBAqVnIMR5DDsp9ucOQAA==",
              "fromFen": "r1bq1bk1/pp3ppp/2p4r/8/2B5/1P2P3/PB1P2PP/R2QR1K1 w - - 1 20",
              "goodNess": 0,
              "id": "7a47503c102ab4c38b9f3112990648f8",
              "month": 12,
              "move": "Rf1",
              "moveIndex": 38,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 23,
              "toFen": "r1bq1bk1/pp3ppp/2p4r/8/2B5/1P2P3/PB1P2PP/R2Q1RK1 b - - 2 20",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "YBCgyBACLVrI4XEEt6Z3usOQAA==",
              "fromFen": "r1bq1bk1/pp3ppp/2p4r/8/2B5/1P2P3/PB1P2PP/R2Q1RK1 b - - 2 20",
              "goodNess": 0,
              "id": "7ad5b1922756d3454a885017990549fd",
              "month": 12,
              "move": "Be6",
              "moveIndex": 39,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 36,
              "toFen": "r2q1bk1/pp3ppp/2p1b2r/8/2B5/1P2P3/PB1P2PP/R2Q1RK1 w - - 3 21",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "MMWAUgQJlJqFHB5DDup6ucOQAA==",
              "fromFen": "r2q1bk1/pp3ppp/2p1b2r/8/2B5/1P2P3/PB1P2PP/R2Q1RK1 w - - 3 21",
              "goodNess": 0,
              "id": "79ee2f8dac20643647dd0b23177b3fcf",
              "month": 12,
              "move": "Bxe6",
              "moveIndex": 40,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 0,
              "toFen": "r2q1bk1/pp3ppp/2p1B2r/8/8/1P2P3/PB1P2PP/R2Q1RK1 b - - 0 21",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AIGhyBACLVrI4XEEt6aXC8OQAA==",
              "fromFen": "r2q1bk1/pp3ppp/2p1B2r/8/8/1P2P3/PB1P2PP/R2Q1RK1 b - - 0 21",
              "goodNess": 0,
              "id": "cb35752a1c2597c3e50471098c47129f",
              "month": 12,
              "move": "Rxe6",
              "moveIndex": 41,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 3,
              "toFen": "r2q1bk1/pp3ppp/2p1r3/8/8/1P2P3/PB1P2PP/R2Q1RK1 w - - 0 22",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QBwoRZBAqVnI4TEE6nq5w5AA",
              "fromFen": "r2q1bk1/pp3ppp/2p1r3/8/8/1P2P3/PB1P2PP/R2Q1RK1 w - - 0 22",
              "goodNess": 0,
              "id": "79b17ca4336e94cd20a53852e7bdd890",
              "month": 12,
              "move": "Qf3",
              "moveIndex": 42,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 2,
              "toFen": "r2q1bk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P2PP/R4RK1 b - - 1 22",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AHlwFRlCoEULOXAEanq5w5AA",
              "fromFen": "r2q1bk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P2PP/R4RK1 b - - 1 22",
              "goodNess": 0,
              "id": "f0b72aec4a4c998156e6405918f05de0",
              "month": 12,
              "move": "Qe8",
              "moveIndex": 43,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 17,
              "toFen": "r3qbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P2PP/R4RK1 w - - 2 23",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QBy8pQgSKDULOXiGQF24w5AA",
              "fromFen": "r3qbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P2PP/R4RK1 w - - 2 23",
              "goodNess": 0,
              "id": "3ad917f692d77bb222644ad846812875",
              "month": 12,
              "move": "Rf2",
              "moveIndex": 44,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 18,
              "toFen": "r3qbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/R5K1 b - - 3 23",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AHlwFRniBFq0kAMEar64w5AA",
              "fromFen": "r3qbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/R5K1 b - - 3 23",
              "goodNess": 0,
              "id": "f977ad2ef5db701ea6097a1e12394a0b",
              "month": 12,
              "move": "Rd8",
              "moveIndex": 45,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 9,
              "toFen": "3rqbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/R5K1 w - - 4 24",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QBy8pQgS6FWzEJxnCBS4w5AA",
              "fromFen": "3rqbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/R5K1 w - - 4 24",
              "goodNess": 0,
              "id": "6f27b61f473bfec7e418bf445a82cb6e",
              "month": 12,
              "move": "Raf1",
              "moveIndex": 46,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 8,
              "toFen": "3rqbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/5RK1 b - - 5 24",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AHlwFRniBFq0EHAEar4Xw5AA",
              "fromFen": "3rqbk1/pp3ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/5RK1 b - - 5 24",
              "goodNess": 0,
              "id": "80892ace23f9aff876a44535562b8f5f",
              "month": 12,
              "move": "Rd7",
              "moveIndex": 47,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 24,
              "toFen": "4qbk1/pp1r1ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/5RK1 w - - 6 25",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QBy8pYgjgV41C4FnCNQFw5AA",
              "fromFen": "4qbk1/pp1r1ppp/2p1r3/8/8/1P2PQ2/PB1P1RPP/5RK1 w - - 6 25",
              "goodNess": 0,
              "id": "622efa10db54f2ce6cf00eaf62cf8663",
              "month": 12,
              "move": "Qf5",
              "moveIndex": 48,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 29,
              "toFen": "4qbk1/pp1r1ppp/2p1r3/5Q2/8/1P2P3/PB1P1RPP/5RK1 b - - 7 25",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AOFxFRniBFpXCwFHoOYLw5AA",
              "fromFen": "4qbk1/pp1r1ppp/2p1r3/5Q2/8/1P2P3/PB1P1RPP/5RK1 b - - 7 25",
              "goodNess": 0,
              "id": "20b64cb1721399ecd02004be28d2582b",
              "month": 12,
              "move": "Red6",
              "moveIndex": 49,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 5,
              "toFen": "4qbk1/pp1r1ppp/2pr4/5Q2/8/1P2P3/PB1P1RPP/5RK1 w - - 8 26",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QA4vpYgjgV41C4FnCNQFw5AA",
              "fromFen": "4qbk1/pp1r1ppp/2pr4/5Q2/8/1P2P3/PB1P1RPP/5RK1 w - - 8 26",
              "goodNess": 0,
              "id": "96fcae58bf73fbc58eb10cf8f1d482f2",
              "month": 12,
              "move": "Qc2",
              "moveIndex": 50,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 12,
              "toFen": "4qbk1/pp1r1ppp/2pr4/8/8/1P2P3/PBQP1RPP/5RK1 b - - 9 26",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AAG3yHjiBFpXCwFHoOYLw5AA",
              "fromFen": "4qbk1/pp1r1ppp/2pr4/8/8/1P2P3/PBQP1RPP/5RK1 b - - 9 26",
              "goodNess": 0,
              "id": "12e75726e5f98408f613a1e0c6603c93",
              "month": 12,
              "move": "Rh6",
              "moveIndex": 51,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 31,
              "toFen": "4qbk1/pp1r1ppp/2p4r/8/8/1P2P3/PBQP1RPP/5RK1 w - - 10 27",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "QIBSxJFAr76zEHiGHNQFw5AA",
              "fromFen": "4qbk1/pp1r1ppp/2p4r/8/8/1P2P3/PBQP1RPP/5RK1 w - - 10 27",
              "goodNess": 0,
              "id": "d2f06b9df3fc10afd577f29e0958ec33",
              "month": 12,
              "move": "g3",
              "moveIndex": 52,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 26,
              "toFen": "4qbk1/pp1r1ppp/2p4r/8/8/1P2P1P1/PBQP1R1P/5RK1 b - - 0 27",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "AAGKjCeOoHW1EHAEt+YLw5AA",
              "fromFen": "4qbk1/pp1r1ppp/2p4r/8/8/1P2P1P1/PBQP1R1P/5RK1 b - - 0 27",
              "goodNess": 0,
              "id": "76a405475132fab6b5dbb1f775b1acfb",
              "month": 12,
              "move": "c5",
              "moveIndex": 53,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 2,
              "toFen": "4qbk1/pp1r1ppp/7r/2p5/8/1P2P1P1/PBQP1R1P/5RK1 w - - 0 28",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IIBSxJGgrr6zEHiGHNQFw5AA",
              "fromFen": "4qbk1/pp1r1ppp/7r/2p5/8/1P2P1P1/PBQP1R1P/5RK1 w - - 0 28",
              "goodNess": 0,
              "id": "04042843893dc1c7d3e5e6d0111d1905",
              "month": 12,
              "move": "Rf5",
              "moveIndex": 54,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 37,
              "toFen": "4qbk1/pp1r1ppp/7r/2p2R2/8/1P2P1P1/PBQP3P/5RK1 b - - 1 28",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UIQDyHiCoHW1EHAEt+YLw5AA",
              "fromFen": "4qbk1/pp1r1ppp/7r/2p2R2/8/1P2P1P1/PBQP3P/5RK1 b - - 1 28",
              "goodNess": 0,
              "id": "f6237b806b579e3626559fec97e822fe",
              "month": 12,
              "move": "b6",
              "moveIndex": 55,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 12,
              "toFen": "4qbk1/p2r1ppp/1p5r/2p2R2/8/1P2P1P1/PBQP3P/5RK1 w - - 0 29",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IHApJRwJir6zEHiGHNQFw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p5r/2p2R2/8/1P2P1P1/PBQP3P/5RK1 w - - 0 29",
              "goodNess": 0,
              "id": "d0104dfb7df7fc0688751fcc88ec9db1",
              "month": 12,
              "move": "R1f2",
              "moveIndex": 56,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 38,
              "toFen": "4qbk1/p2r1ppp/1p5r/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 b - - 1 29",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UIQDJeOJI2hdCgEEt+YLw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p5r/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 b - - 1 29",
              "goodNess": 0,
              "id": "391536baf4bb3265a971e488920c7e70",
              "month": 12,
              "move": "Re6",
              "moveIndex": 57,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 7,
              "toFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 w - - 2 30",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IByXUsKRoK6+sxB4hkABw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 w - - 2 30",
              "goodNess": 0,
              "id": "fbf5507941faff06ae934c0944698cad",
              "month": 12,
              "move": "Qc3",
              "moveIndex": 58,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 15,
              "toFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 b - - 3 30",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UI9wXEqGOILWpRBAoOYLw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 b - - 3 30",
              "goodNess": 0,
              "id": "25ea4289fa8a2c4fd42cc530c0799050",
              "month": 12,
              "move": "Red6",
              "moveIndex": 59,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 4,
              "toFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 w - - 4 31",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IA6Xeks4EtRVsxB4hkABw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 w - - 4 31",
              "goodNess": 0,
              "id": "ff922e10da3613e275debf2fc64ddd6c",
              "month": 12,
              "move": "Qc2",
              "moveIndex": 60,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 32,
              "toFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 b - - 5 31",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UITDVTKeOILWpRBAoOYLw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 b - - 5 31",
              "goodNess": 0,
              "id": "ab3674bca9dbc1153a11ad43c82675a3",
              "month": 12,
              "move": "Re6",
              "moveIndex": 61,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 23,
              "toFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 w - - 6 32",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IByXUsKRoK6+sxB4hkABw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 w - - 6 32",
              "goodNess": 0,
              "id": "9bd91d4ca5bb31c2141cb6473d9f88a6",
              "month": 12,
              "move": "Qc3",
              "moveIndex": 62,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 15,
              "toFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 b - - 7 32",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UI9wXEqGOILWpRBAoOYLw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 b - - 7 32",
              "goodNess": 0,
              "id": "f35b49300b2556d48a9326eba125952e",
              "month": 12,
              "move": "Red6",
              "moveIndex": 63,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 4,
              "toFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 w - - 8 33",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IA6Xeks4EtRVsxB4hkABw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1PQ1P1P1/PB1P1R1P/6K1 w - - 8 33",
              "goodNess": 0,
              "id": "1e2a387c337ecfb5ee210c6061d50eba",
              "month": 12,
              "move": "Qc2",
              "moveIndex": 64,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 32,
              "toFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 b - - 9 33",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "black",
              "activeElo": 2768,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "UITDVTKeOILWpRBAoOYLw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p1r4/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 b - - 9 33",
              "goodNess": 0,
              "id": "1283f8276a4a706fe734c3a2075cf80f",
              "month": 12,
              "move": "Re6",
              "moveIndex": 65,
              "opening": "Ruy Lopez",
              "passiveElo": 2775,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "toBoard": 23,
              "toFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 w - - 10 34",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            },
            {
              "activeColor": "white",
              "activeElo": 2775,
              "black": "Giri, A",
              "blackElo": 2768,
              "blackFideId": "24116068",
              "blackTitle": "GM",
              "day": 10,
              "eco": "C67",
              "event": "6th London Classic 2014",
              "fromBoard": "IByXUsKRoK6+sxB4hkABw5AA",
              "fromFen": "4qbk1/p2r1ppp/1p2r3/2p2R2/8/1P2P1P1/PBQP1R1P/6K1 w - - 10 34",
              "goodNess": 0,
              "id": "885fd4687b3523ca89981a81dde5142b",
              "month": 12,
              "opening": "Ruy Lopez",
              "passiveElo": 2768,
              "result": "1/2-1/2",
              "round": "1.3",
              "site": "London ENG",
              "variation": "Berlin defence, open variation",
              "white": "Nakamura, Hi",
              "whiteElo": 2775,
              "whiteFideId": "2016192",
              "whiteTitle": "GM",
              "year": 2014
            }
          ];
          assert.deepEqual(documents, expected);
        });
      }
    };
    
  });
